// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_pause  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_trying 22
#define SYS_tryint 23
#define SYS_semget    24
#define SYS_semwait   25
#define SYS_sempost   26
#define SYS_semclose  27
#define SYS_getprocinfo  28
#define SYS_signal_init 29
#define SYS_signal_send 30
#define SYS_signal_handle 31
#define SYS_clone 32
#define SYS_mutex_create 33
#define SYS_mutex_lock 34
#define SYS_mutex_unlock 35
#define SYS_sigmask 36
#define SYS_getproccount 37
#define SYS_sendmsg      38
#define SYS_createlock   39
#define SYS_threadcreate 40
#define SYS_sendsignal   41
